name: build

# build on c/cpp changes or workflow changes
on:
  - push
  - pull_request

jobs:

  linux-gl:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic
      env: { LANG: "C.UTF-8" }
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          apt-get update
          apt-get install g++ cmake libxi-dev libgl1-mesa-dev libpng-dev libjpeg-dev zlib1g-dev -qyy

      - name: Build
        run: |
          cmake . -DUSE_SDL2=OFF
          make VERBOSE=1 -j2

      - name: Test
        run: |
          ctest --output-on-failure

      - name: Package
        run: |
          make DESTDIR=$PWD/_install install
          tar -c -I "gzip -9" -f irrlicht-linux.tar.gz -C ./_install/usr/local .

      - uses: actions/upload-artifact@v3
        with:
          name: irrlicht-linux
          path: ./irrlicht-linux.tar.gz

  linux-gles:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic
      env: { LANG: "C.UTF-8" }
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          apt-get update
          apt-get install g++ cmake libxi-dev libgles2-mesa-dev libpng-dev libjpeg-dev zlib1g-dev xvfb -qyy

      - name: Build
        run: |
          cmake . -DBUILD_EXAMPLES=1 -DUSE_SDL2=OFF -DENABLE_OPENGL=OFF -DENABLE_GLES2=ON
          make -j2

      - name: Test (headless)
        run: |
          cd bin/Linux
          ./AutomatedTest null

      - name: Test (Xvfb)
        run: |
          cd bin/Linux
          LIBGL_ALWAYS_SOFTWARE=true xvfb-run ./AutomatedTest ogles2
